import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/components/ConvexClientProvider";
import Navbar from "@/components/Navbar";
import { CartProvider } from "@/context/CartContext"; // <--- Import this
// 1. Import the Convex Provider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Voloostore", // Updated title for your project
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // 2. ClerkProvider stays on the outside (Top Level)
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* ზედმეტია პროსტა დავაკომენტარე, მოერიდე ყოველთვის ლეიაუთში
           რეგისტრაციის აუთენტიფიკაციის და ავტორიზაციის დამატებას 
          ეს სეოსთვისაა საჭირო მიხვდები მერე  */}
          {/* <header className="flex justify-end items-center p-4 gap-4 h-16">

            <SignedOut>
              <SignInButton />
              <SignUpButton>
                <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header> */}

          {/* 3. ConvexClientProvider wraps the children (inside the body) */}
          <ConvexClientProvider>
            <CartProvider>

              {/* navbars აქ არაფერი არ ესაქმება მარტო wrappers and providers
               უბდა იხმარო its the best practice and learn how to write clean code 
                გემინაიმ და არც სხვა ხელოვნურმა ინტელექტმა არ იცის მაგის შემოთავაზება 
                არც გიკონტროლებს არასოდეს და მიეჩვიე აქედანვე.
                client side კომპონენტები დაჟე landing page-ზეც კომპონტებად არენდერე კოდი არ გამოიტანო და 
                გაითვალისწინე რომ კონვექსის ფუნქციები ყველა client side არის 
                ხოლო ყველა მთავარი ლოგიკა და ალგორითმი უნდა იყოს იზოლირებული client
                side-სგან მაქსიმალურად*/}
              <Navbar />
              {children}
            </CartProvider>
          </ConvexClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
